### PR TITLE
Add support for files

### PR DESCRIPTION
**Pull request by sebbert**

### CODE REVIEW

**Review by pavelzubarev — APPROVED** [review]

**Review by mathialo — APPROVED** [review]

**Comment by pavelzubarev** [comment]
btw, sequences are also missing

**Comment by sebbert** [comment]
Good catch 👍

**Comment by sebbert** [comment]
We should probably just use a string here, so we don't have to keep the CLI in sync

**Review by pavelzubarev — APPROVED** [review]
🚀

**Comment by pavelzubarev** [comment]
> We should probably just use a string here, so we don't have to keep the CLI in sync

Yes and No :) If you want to be explicit and don't validate it yourself you use types. but then a better error message is definitely needed

**Comment by sebbert** [comment]
Ideally, the backend would have an endpoint that lists supported destinations. Ideally.

**Pull request merged**
