### PR TITLE
Add ignoreNullFields support

### PR DESCRIPTION
**Pull request by vvemel**

### CODE REVIEW

**Comment by mathialo** [comment]
I was about to release 2.1.2 to get the docker image published, but let's wait for this as well 🙂

**Comment by vvemel** [comment]
> I was about to release 2.1.2 to get the docker image published, but let's wait for this as well 🙂

I can use some help for setting default value on manifest parser. It may take time with my unexisting C# knowledge :D

**Comment by mathialo** [comment]
> I can use some help for setting default value on manifest parser. It may take time with my unexisting C# knowledge :D

I'll have to leave now, but I/we can have a look at it tomorrow morning 🙂

**Comment by vvemel** [comment]
> > I can use some help for setting default value on manifest parser. It may take time with my unexisting C# knowledge :D
> 
> I'll have to leave now, but I/we can have a look at it tomorrow morning 🙂

Super!

**Review by mathialo — APPROVED** [review]
Nice!

**Comment by vvemel** [comment]
> Nice!

Could you let me know when you release the new version? Ana was asking about nullFieldUpdate support on jetfire-cli :)

**Pull request merged**
